Home/steps
Junfolio/junfolio pull request #91
Opened 2023-05-11 19:25 UTC by AnnaSidiakina

Add  section Steps (Етапи  нашої роботи) to Home page.

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +import { useRef } from 'react';
Better to split imports
1.libs
free space
2. cunstom components

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +import step7 from '@public/images/homePage/steps/step7.svg';
make index file to export there all photos and then import it here from index file 
![Знімок екрана 2023-05-11 о 22 35 33](https://github.com/Junfolio/junfolio/assets/126114463/89b38685-2cde-47f8-9462-2b8db95ad0d9)
![Знімок екрана 2023-05-11 о 22 34 54](https://github.com/Junfolio/junfolio/assets/126114463/f7b751e2-77a0-43e7-949a-98feb9b3c57d)

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +  ];
use separate file for constant values and than import it here

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +  // };
Dont leave dead code

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +    if (mousePosition.x > screen.width - (screen.width / 100) * 14) {
What does mean 100 and 14 and why they are not constants

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +  }, [mousePosition]);
Use reverse audit condition and dont use else block
read airbnb convention doc in useful links

2023-05-11 19:45 UTC, painlalala commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +    <>
why u use here empty tags?

2023-05-11 19:45 UTC, painlalala commented on src/components/Portfolio/ProjectInfo/Slider/Slider.jsx
> +} from './Slider.styled';
separate imports

2023-05-11 19:45 UTC, painlalala commented on src/pages/index.js
> +        <Part6Steps />
User semantic names

2023-05-12 06:27 UTC, forze961 requested changes

2023-05-12 06:27 UTC, forze961 commented on src/styles/Theme.jsx
> +    xxxxxxxl: '96px',
Need a better name for params

2023-05-12 06:27 UTC, forze961 commented on src/styles/GlobalStyles.jsx
> +
Need to align whitespaces

2023-05-12 06:27 UTC, forze961 commented on src/components/common/Container/Container.styled.js
> +import { theme } from '@component/styles/Theme';
Duplicate import

2023-05-12 06:27 UTC, forze961 commented on src/components/Portfolio/ProjectInfo/Slider/Slider.jsx
> +        onSlideChange={() => console.log('slide change', swiperRef.current)}
Not critical, but we shouldn't use console.log in prod

2023-05-12 06:27 UTC, forze961 commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.styled.js
> +export const StyledSlider = styled(Swiper)``;
Nested '`'

2023-05-12 07:33 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +import { useRef } from 'react';
done

2023-05-12 07:48 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +import step7 from '@public/images/homePage/steps/step7.svg';
done

2023-05-12 07:55 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +  ];
done

2023-05-12 08:01 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +    if (mousePosition.x > screen.width - (screen.width / 100) * 14) {
done

2023-05-12 08:53 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +  }, [mousePosition]);
I am not sure that I got it right, but I removed else block

2023-05-12 08:53 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.jsx
> +    <>
not anymore

2023-05-12 08:54 UTC, AnnaSidiakina commented on src/components/Portfolio/ProjectInfo/Slider/Slider.jsx
> +} from './Slider.styled';
This is Vladimir's file, I will tell him about it

2023-05-12 09:09 UTC, AnnaSidiakina commented on src/pages/index.js
> +        <Part6Steps />
done

2023-05-12 09:20 UTC, AnnaSidiakina commented on src/styles/Theme.jsx
> +    xxxxxxxl: '96px',
Well, I have an idea how to make it better. But the thing is that we have now 15 fontSizes. I will talk with designers, maybe we can cut some of them

2023-05-12 09:28 UTC, AnnaSidiakina commented on src/styles/GlobalStyles.jsx
> +
done

2023-05-12 09:30 UTC, AnnaSidiakina commented on src/components/common/Container/Container.styled.js
> +import { theme } from '@component/styles/Theme';
I can't see it

2023-05-12 09:33 UTC, AnnaSidiakina commented on src/components/Home/HomeParts/HomePart6Steps/HomePart6Steps.styled.js
> +export const StyledSlider = styled(Swiper)``;
removed

2023-05-12 15:44 UTC, forze961 approved these changes

2023-05-12 15:44 UTC, merged