Vs/circles
Junfolio/junfolio pull request #93
Opened 2023-05-13 11:46 UTC by VladimirSt13

1) Added decorative ellipses to the hero section on the home page
2) Some minor fixes

2023-05-13 12:44 UTC, AnnaSidiakina approved these changes

2023-05-15 07:54 UTC, forze961 requested changes

2023-05-15 07:54 UTC, forze961 commented on src/components/Home/HomeParts/HeroSection.jsx
> +  // overflow: 'hidden',
Remove unused or add todo

2023-05-15 07:54 UTC, forze961 commented on src/components/Home/HomeParts/HeroSection.jsx
> +            <div style={{ position: 'relative' }}>
If we using object styled components why we need to use Inline style?

2023-05-15 07:54 UTC, forze961 commented on src/components/Portfolio/Portfolio/Portfolio.jsx
> +      {/* <Container>
We need a comment?

2023-05-15 07:54 UTC, forze961 commented on src/components/Home/HomeParts/JuniorsSection.jsx
> +    handleAnimation(
We can reuse this code. I see same code below.

2023-05-15 09:22 UTC, VladimirSt13 commented on src/components/Home/HomeParts/HeroSection.jsx
> +            <div style={{ position: 'relative' }}>
Added styled div

2023-05-15 09:24 UTC, VladimirSt13 commented on src/components/Portfolio/Portfolio/Portfolio.jsx
> +      {/* <Container>
deleted

2023-05-15 09:37 UTC, VladimirSt13 commented on src/components/Home/HomeParts/JuniorsSection.jsx
> +    handleAnimation(
this code - is calling function with some parameters, blelow - calling the same function with other parameters. How to reuse this code?

2023-05-15 19:19 UTC, forze961 commented on src/components/Home/HomeParts/JuniorsSection.jsx
> +    handleAnimation(
> this code - is calling function with some parameters, blelow - calling the same function with other parameters. How to reuse this code?

For example: Junior & Customer sections have very similar code.  Nice to have a a global section container where we can describe and then call  reusable functions or JSX. Then on index.js call <GlobalSection type=...>

2023-05-17 18:13 UTC, painlalala commented on src/components/Portfolio/Portfolio/Portfolio.jsx
>      } catch (error) {
???

2023-05-17 18:42 UTC, VladimirSt13 commented on src/components/Portfolio/Portfolio/Portfolio.jsx
>      } catch (error) {
add alert message: Не вдалось отримати проекти

2023-05-18 14:22 UTC, forze961 approved these changes

2023-05-18 14:23 UTC, merged